apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: trudesk
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rp3
  hostPath:
    path: /mnt/ssd1/mongo
    type: DirectoryOrCreate
