- name: Ensure vikunja namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
    state: present

- name: Check if PVC already exists
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}"
    api_version: v1
    kind: PersistentVolumeClaim
    namespace: "{{ namespace }}"
    name: vikunja-files
  register: pvc_info
  failed_when: false
  changed_when: false

- name: Create PVC for Vikunja SQLite storage (only if missing)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition: "{{ lookup('template', 'vikunja-pvc.yaml.j2') }}"
  when: pvc_info.resources | length == 0

- name: Skip PVC creation if it already exists
  debug:
    msg: "PVC 'vikunja-files' already exists. Skipping creation."
  when: pvc_info.resources | length > 0

- name: Create backup script for PVC data
  ansible.builtin.copy:
    dest: /usr/local/bin/backup_vikunja_pvc.sh
    mode: '0755'
    owner: root
    group: root
    content: |
      #!/bin/bash
      timestamp=$(date +\%F_\%H-\%M-\%S)
      backup_dir="/mnt/ssd1/vikunja_backups"
      mkdir -p "$backup_dir"
      tar -czf "$backup_dir/vikunja_backup_$timestamp.tar.gz" /var/lib/kubelet/pods/*/volumes/kubernetes.io~local-volume/pvc-*/files

- name: Ensure daily cron job exists for PVC backups
  ansible.builtin.cron:
    name: "Backup Vikunja PVC daily"
    minute: "0"
    hour: "2"
    job: "/usr/local/bin/backup_vikunja_pvc.sh"

- name: Deploy Vikunja (API + Frontend)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition: "{{ lookup('template', 'vikunja-deployment.yaml.j2') }}"

- name: Expose Vikunja services (NodePort)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition: "{{ lookup('template', 'vikunja-service.yaml.j2') }}"

- name: Deploy ClusterIP service for Prometheus exporter
  kubernetes.core.k8s:
    state: present
    kubeconfig: /home/alien/.kube/config
    definition: "{{ lookup('template', 'vikunja-exporter-service.yaml.j2') }}"
