---
- name: Disable password authentication for SSH
  hosts: all  # Runs on all Raspberry Pis in the inventory
  become: true  # Run as root
  tasks:
    - name: Ensure PasswordAuthentication is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes

    - name: Ensure ChallengeResponseAuthentication is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication no'
        state: present

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
