- name: Nuke FreeScout and MariaDB from orbit
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete namespace (and all contained resources)
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: freescout
